server:
  name: "project-api"
  addr: "127.0.0.1:80"
zap:
  DebugFileName: "/Users/kezi/GolandProjects/msProject/logs/debug/project-debug.log"
  InfoFileName: "/Users/kezi/GolandProjects/msProject/logs/info/project-info.log"
  WarnFileName: "/Users/kezi/GolandProjects/msProject/logs/project-error.log"
  MaxSize: 500
  MaxAge: 3
  MaxBackups: 3
redis:
  host: ""
  port: "6379"
  password: ""
  db: 0