server:
  name: "project-user"
  addr: ":80"
zap:
  DebugFileName: "/Users/kezi/GolandProjects/msProject/logs/debug/project-debug.log"
  InfoFileName: "/Users/kezi/GolandProjects/msProject/logs/info/project-info.log"
  WarnFileName: "/Users/kezi/GolandProjects/msProject/logs/project-error.log"
  MaxSize: 500
  MaxAge: 3
  MaxBackups: 3
redis:
  host: "175.178.19.5"
  port: "6379"
  Password: "kezi520"
  db: 0